#pragma config(Sensor, in2,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in3,    middleLine,     sensorLineFollower)
#pragma config(Sensor, in4,    rightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          turnMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool finished = false; 
int trigger = 0; 
task main()
{


	while(finished == false && 1)
	{
		//line is in middle, activate both motors
		if (SensorValue[leftLine] <= 3000 && SensorValue[rightLine] <= 3000 && SensorValue[middleLine] >= 3000)
		{

			startMotor(motor1, 35);
			startMotor(motor2, 35);

		}
		//line is left, turn right
		else if (SensorValue[leftLine] >= 3000 && SensorValue[rightLine] <= 3000 && SensorValue[middleLine] <= 3000)
		{
			stopMotor(motor1);
			stopMotor(motor2);
			startMotor(turnMotor);

		}
		//line is right, turn left
		else if (SensorValue[leftLine] <= 3000 && SensorValue[rightLine] >= 3000 && SensorValue[middleLine] <= 3000)
		{
			stopMotor(motor1);
			stopMotor(motor2);
			startMotor(turnMotor, -127);
		}
		//if all line detectors detect more than 3000, turn off.
		else if (SensorValue[leftLine] >= 3000 && SensorValue[rightLine] >= 3000 && SensorValue[middleLine] >= 3000)
		{	trigger+; 
			bool finished = true;
			startMotor(motor1,30);
			startMotor(motor2,30);
			wait(1.5);
			stopMotor(motor1);
			stopMotor(motor2);
		}
	}
}
