#pragma config(Sensor, port3,  middleLine,     sensorReflection)
#pragma config(Sensor, port4,  rightLine,      sensorReflection)
#pragma config(Sensor, port9,  startButton,    sensorTouch)
#pragma config(Motor,  motor1,           ,             tmotorVexIQ, openLoop)
#pragma config(Motor,  motor2,           ,             tmotorVexIQ, openLoop, reversed)
#pragma config(Motor,  motor10,         turn,          tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

bool buttonStop = false;

while(1==1)
{
//untilBump(startButton, 0);
 if (SensorValue(startButton) == 1 && buttonStop == false)
{
while(SensorValue[leftLine] < 3000) {
    //WAIT TILL ON BLACK LINE
		untilDark(3000, middleLine);
		startMotor(turn/*change value later*/);
}
while(SensorValue[middleLine, 3000]){
	startMotor(motor1, 172);
	startMotor(motor2, 172);
}

while(SensorValue[rightLine] < 3000){
	startMotor(turn/*change value later*/);

}



buttonStop = false;
}
}
}
