#pragma config(Sensor, in2,    leftLine,       sensorReflection)
#pragma config(Sensor, in3,    middleLine,     sensorReflection)
#pragma config(Sensor, in4,    rightLine,      sensorReflection)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          turnMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool light1Activated = false;


task main()
{

bool buttonStop = false;


	while(1==1)
	{
		//start forward motors
		 if (SensorValue(startButton) == 1 && buttonStop == false)
		{
			//
			if (SensorValue[leftLine] > 2500) 
			{
				light1Activated = true;
				startMotor(turnMotor, 127);
			}
		}
	buttonStop = false;
	}
}
